"""empty message

Revision ID: 7c97b9322973
Revises: 3ddd54edbc7c
Create Date: 2022-03-24 16:18:48.572881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c97b9322973'
down_revision = '3ddd54edbc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('question', 'context')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('context', mysql.TEXT(), nullable=False))
    op.drop_column('question', 'content')
    # ### end Alembic commands ###
